/*
 * The Lucide icon set the comp uses (spec §6.15), addressed by the same
 * kebab-case names the data files carry. Tree-shaken named imports — no UMD
 * script, no dynamic import.
 *
 * Icons are decorative by default (`aria-hidden`); pass `title` only when the
 * icon is the *only* content of a control, and prefer an `aria-label` on the
 * button itself.
 */

import {
  Accessibility,
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Baby,
  Banknote,
  Bell,
  BellOff,
  BellPlus,
  Bike,
  BookOpen,
  Briefcase,
  Cake,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarOff,
  CalendarPlus,
  CalendarX,
  Car,
  ChartColumn,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardCheck,
  Clock,
  Coins,
  Copy,
  CornerDownRight,
  CreditCard,
  DoorOpen,
  Download,
  Droplet,
  Eye,
  FileDown,
  FileSpreadsheet,
  FileText,
  FlaskConical,
  Flower2,
  Footprints,
  Gauge,
  Gem,
  Gift,
  GlassWater,
  Globe,
  GraduationCap,
  Hand,
  HandCoins,
  Hash,
  HeartHandshake,
  Home,
  Info,
  Layers,
  LayoutDashboard,
  Leaf,
  LifeBuoy,
  Lightbulb,
  Link,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  MapPin,
  Menu,
  MessageSquare,
  Minus,
  Moon,
  Navigation,
  Package,
  Paintbrush,
  Palette,
  PenTool,
  PersonStanding,
  Phone,
  Plus,
  Receipt,
  Repeat,
  Reply,
  RotateCcw,
  Scissors,
  Search,
  SearchX,
  Send,
  Settings,
  Settings2,
  Share2,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Sprout,
  Star,
  StickyNote,
  Sun,
  Sunrise,
  Sunset,
  Tag,
  ThumbsUp,
  Ticket,
  TicketPercent,
  TrainFront,
  Trash2,
  TriangleAlert,
  Truck,
  User,
  UserCog,
  UserPlus,
  UserRound,
  UserRoundX,
  Users,
  Wallet,
  Waves,
  X,
  XCircle,
  Zap,
} from "lucide-react";
import type { CSSProperties } from "react";

export const ICONS = {
  accessibility: Accessibility,
  activity: Activity,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  baby: Baby,
  banknote: Banknote,
  bell: Bell,
  "bell-off": BellOff,
  "bell-plus": BellPlus,
  bike: Bike,
  "book-open": BookOpen,
  briefcase: Briefcase,
  cake: Cake,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  "calendar-clock": CalendarClock,
  "calendar-days": CalendarDays,
  "calendar-off": CalendarOff,
  "calendar-plus": CalendarPlus,
  "calendar-x": CalendarX,
  car: Car,
  "chart-column": ChartColumn,
  check: Check,
  "check-circle-2": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "clipboard-check": ClipboardCheck,
  clock: Clock,
  coins: Coins,
  copy: Copy,
  "corner-down-right": CornerDownRight,
  "credit-card": CreditCard,
  "door-open": DoorOpen,
  download: Download,
  droplet: Droplet,
  eye: Eye,
  "file-down": FileDown,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  "flask-conical": FlaskConical,
  "flower-2": Flower2,
  footprints: Footprints,
  gauge: Gauge,
  gem: Gem,
  gift: Gift,
  "glass-water": GlassWater,
  globe: Globe,
  "graduation-cap": GraduationCap,
  hand: Hand,
  "hand-coins": HandCoins,
  hash: Hash,
  "heart-handshake": HeartHandshake,
  home: Home,
  info: Info,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  leaf: Leaf,
  "life-buoy": LifeBuoy,
  lightbulb: Lightbulb,
  link: Link,
  "loader-circle": LoaderCircle,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  "mail-check": MailCheck,
  "map-pin": MapPin,
  menu: Menu,
  "message-square": MessageSquare,
  minus: Minus,
  moon: Moon,
  navigation: Navigation,
  package: Package,
  paintbrush: Paintbrush,
  palette: Palette,
  "pen-tool": PenTool,
  "person-standing": PersonStanding,
  phone: Phone,
  plus: Plus,
  receipt: Receipt,
  repeat: Repeat,
  reply: Reply,
  "rotate-ccw": RotateCcw,
  scissors: Scissors,
  search: Search,
  "search-x": SearchX,
  send: Send,
  settings: Settings,
  "settings-2": Settings2,
  "share-2": Share2,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  smartphone: Smartphone,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  "sticky-note": StickyNote,
  sun: Sun,
  sunrise: Sunrise,
  sunset: Sunset,
  tag: Tag,
  "thumbs-up": ThumbsUp,
  ticket: Ticket,
  "ticket-percent": TicketPercent,
  "train-front": TrainFront,
  "trash-2": Trash2,
  "triangle-alert": TriangleAlert,
  truck: Truck,
  user: User,
  "user-cog": UserCog,
  "user-plus": UserPlus,
  "user-round": UserRound,
  "user-round-x": UserRoundX,
  users: Users,
  wallet: Wallet,
  waves: Waves,
  x: X,
  "x-circle": XCircle,
  zap: Zap,
} as const;

export type IconName = keyof typeof ICONS;

export interface IconProps {
  /** Kebab-case Lucide name. Unknown names render nothing. */
  name: IconName | string;
  size?: number;
  /** Defaults to `currentColor`. */
  color?: string;
  strokeWidth?: number;
  className?: string;
  style?: CSSProperties;
  /** Accessible label; when omitted the icon is `aria-hidden`. */
  title?: string;
}

export function Icon({
  name,
  size = 16,
  color,
  strokeWidth = 2,
  className,
  style,
  title,
}: IconProps) {
  const Cmp = ICONS[name as IconName];
  if (!Cmp) return null;
  return (
    <Cmp
      size={size}
      color={color}
      strokeWidth={strokeWidth}
      className={className}
      style={{ flexShrink: 0, ...style }}
      aria-hidden={title ? undefined : true}
      aria-label={title}
      role={title ? "img" : undefined}
    />
  );
}
